const KEY='cheptulelAdminV3';
const toggle=document.querySelector('.menu-toggle');const navWrap=document.querySelector('.nav-wrap');toggle?.addEventListener('click',()=>navWrap.classList.toggle('menu-open'));document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',()=>navWrap.classList.remove('menu-open')));document.getElementById('year').textContent=new Date().getFullYear();
const db=JSON.parse(localStorage.getItem(KEY)||'null');
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function money(v){const n=Number(v);return Number.isFinite(n)&&n>0?`KES ${n.toLocaleString()}`:(v||'To be confirmed')}
function renderDynamic(){if(!db)return;
 const projects=(db.projects||[]);const pc=document.querySelector('.project-grid');if(pc&&projects.length){pc.innerHTML=projects.map(x=>{const p=Number(x.target)>0?Math.max(0,Math.min(100,Math.round(Number(x.raised||0)/Number(x.target)*100))):0;const image=x.image?`<img src="${esc(x.image)}" alt="${esc(x.name)}" style="width:100%;height:100%;object-fit:cover">`:'🏗️';return `<article class="project-card"><div class="project-image">${image}<span>${esc(x.status)}</span></div><div class="project-body"><div class="project-meta"><span>${esc(x.category||'DEVELOPMENT')}</span><span>${p}% FUNDED</span></div><h3>${esc(x.name)}</h3><p>${esc(x.description)}</p><div class="progress-label"><span>Funding progress</span><b>${p}%</b></div><div class="progress"><i style="width:${p}%"></i></div><div class="money"><span>Target <b>${money(x.target)}</b></span><span>Raised <b>${money(x.raised)}</b></span></div>${x.update?`<p class="project-update"><b>Latest update:</b> ${esc(x.update)}</p>`:''}<a class="btn btn-outline" href="#contact" data-support-project="${esc(x.name)}">Support this project</a></div></article>`}).join('')}
 const gallery=(db.gallery||[]).filter(x=>x.approved);const gc=document.querySelector('.gallery-grid');if(gc&&gallery.length){gc.innerHTML=gallery.slice(0,8).map((x,i)=>`<div class="gallery-item ${i===0?'large':''}"><img src="${esc(x.url)}" alt="${esc(x.title)}" style="width:100%;height:100%;object-fit:cover"><div class="gallery-caption"><small>${esc(x.category)} · ${esc(x.title)}</small></div></div>`).join('')}
 const news=(db.news||[]);const nc=document.querySelector('.news-grid');if(nc&&news.length){nc.innerHTML=news.slice(0,6).map(x=>`<article class="news-card"><div class="news-date">${esc(x.category)}</div><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p><a href="#contact">Contact school →</a></article>`).join('')}
 const s=db.settings||{};document.querySelectorAll('.contact-list p').forEach(p=>{const t=p.textContent;if(t.includes('Phone')&&s.phone)p.innerHTML='<b>Phone</b><br>'+esc(s.phone);if(t.includes('Email')&&s.email)p.innerHTML='<b>Email</b><br>'+esc(s.email)});
 document.querySelectorAll('[data-support-project]').forEach(a=>a.addEventListener('click',()=>{setTimeout(()=>{const sel=document.querySelector('#support-area');if(sel)sel.value='Support project: '+a.dataset.supportProject},50)}));
}
function submitForm(e){e.preventDefault();const form=e.target;const name=form.querySelector('input[type="text"]')?.value||'';const email=form.querySelector('input[type="email"]')?.value||'';const select=form.querySelector('select');const area=select?.value||'General enquiry';const message=form.querySelector('textarea')?.value||'';const store=JSON.parse(localStorage.getItem(KEY)||'null')||{projects:[],news:[],gallery:[],sponsors:[],enquiries:[],settings:{}};store.enquiries=store.enquiries||[];store.enquiries.unshift({id:crypto.randomUUID(),name,email,support_area:area,message,phone:'',date:new Date().toISOString()});localStorage.setItem(KEY,JSON.stringify(store));document.getElementById('form-message').textContent='Thank you. Your enquiry has been saved for the school administration in this browser.';form.reset();return false}
renderDynamic();
