const API=(window.CHEPTULEL_API||'http://127.0.0.1:5000/api').replace(/\/$/,'');let token=localStorage.getItem('cheptulelAdminToken');
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function api(path,opts={}){opts.headers={...(opts.headers||{}),...(token?{Authorization:'Bearer '+token}:{})};const r=await fetch(API+path,opts);let d={};try{d=await r.json()}catch{}if(r.status===401){logout();throw Error('Session expired')}if(!r.ok)throw Error(d.error||'Request failed');return d}
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function money(v){return Number(v)>0?`KES ${Number(v).toLocaleString()}`:'To be confirmed'}
function progress(x){return x.target>0?Math.min(100,Math.round(x.raised/x.target*100)):0}
function render(id,arr,fn){$(id).innerHTML=arr.length?arr.map(fn).join(''):'<div class="admin-card"><p class="hint">No records yet.</p></div>'}
async function loadData(){const d=await api('/admin/data');$('statProjects').textContent=d.projects.length;$('statNews').textContent=d.news.length;$('statGallery').textContent=d.gallery.length;$('statSponsors').textContent='—';$('statEnquiries').textContent=d.enquiries.length;
 render('projectList',d.projects,x=>`<div class="list-item"><div class="list-main">${x.image?`<img class="thumb" src="${esc(API+x.image)}" alt="">`:''}<div><h3>${esc(x.name)}</h3><p>${esc(x.category)} · ${esc(x.status)} · ${progress(x)}% funded</p><p>Target: ${money(x.target)} · Raised: ${money(x.raised)}</p><p>${esc(x.description)}</p><p><b>Latest update:</b> ${esc(x.update||'No update')}</p></div></div><button class="delete" onclick="removeItem('/admin/projects/${x.id}')">Delete</button></div>`);
 render('newsList',d.news,x=>`<div class="list-item"><div><h3>${esc(x.title)}</h3><p>${esc(x.category)} · ${new Date(x.created_at).toLocaleDateString()}</p><p>${esc(x.body)}</p></div><button class="delete" onclick="removeItem('/admin/news/${x.id}')">Delete</button></div>`);
 render('galleryList',d.gallery,x=>`<div class="list-item"><div class="list-main"><img class="thumb" src="${esc(API+x.url)}" alt="${esc(x.title)}"><div><h3>${esc(x.title)}</h3><p>${esc(x.category)} · ${x.published?'Published':'Pending review'}</p><p>${esc(x.caption||'')}</p></div></div><button class="delete" onclick="removeItem('/admin/gallery/${x.id}')">Delete</button></div>`);
 render('enquiryList',d.enquiries,x=>`<div class="list-item"><div><h3>${esc(x.name)} ${x.organization?`— ${esc(x.organization)}`:''}</h3><p>${esc(x.email)} · ${esc(x.phone||'No phone')} · ${esc(x.support_area||'General support')} · <b>${esc(x.status)}</b></p><p>${esc(x.message)}</p><small>${new Date(x.created_at).toLocaleString()}</small></div><button class="delete" onclick="removeItem('/admin/enquiries/${x.id}')">Delete</button></div>`);
 for(const [k,v] of Object.entries(d.settings||{})){const el=document.querySelector(`[name="${k}"]`);if(el)el.value=v||''}
}
async function removeItem(path){if(!confirm('Remove this item?'))return;try{await api(path,{method:'DELETE'});await loadData();toast('Item removed')}catch(e){toast(e.message)}}window.removeItem=removeItem;
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('authError').textContent='';try{const d=await api('/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('loginEmail').value,password:$('loginPassword').value})});token=d.access_token;localStorage.setItem('cheptulelAdminToken',token);showAdmin();await loadData()}catch(err){$('authError').textContent=err.message}});
function showAdmin(){$('authScreen').classList.add('hidden')}function logout(){token=null;localStorage.removeItem('cheptulelAdminToken');$('authScreen').classList.remove('hidden')}$('logout')?.addEventListener('click',logout);
document.querySelectorAll('.side').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.side').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.panel).classList.add('active')}));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>document.querySelector(`[data-panel="${b.dataset.go}"]`)?.click()));
$('projectForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/admin/projects',{method:'POST',body:new FormData(e.target)});e.target.reset();await loadData();toast('Project added')}catch(err){toast(err.message)}});
$('newsForm').addEventListener('submit',async e=>{e.preventDefault();try{const x=Object.fromEntries(new FormData(e.target));await api('/admin/news',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(x)});e.target.reset();await loadData();toast('News published')}catch(err){toast(err.message)}});
$('galleryForm').addEventListener('submit',async e=>{e.preventDefault();try{const fd=new FormData(e.target);fd.set('published',e.target.approved.checked?'true':'false');await api('/admin/gallery',{method:'POST',body:fd});e.target.reset();await loadData();toast('Photo uploaded')}catch(err){toast(err.message)}});
$('settingsForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/admin/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});toast('School settings saved')}catch(err){toast(err.message)}});
if(token){showAdmin();loadData().catch(()=>{})}
